# --- docker-compose.yml ---
# Note: Compose V2 ignores the top-level `version` key. Removed to avoid warnings.
services:
  db:
    image: postgres:15
    env_file:
      - ./backend/.env 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8009:8000"
    volumes:
      - ./backend:/app

  nginx_dev:
    image: nginx:alpine
    container_name: spendtracker_nginx_dev
    network_mode: host
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
 
volumes:
  pgdata: {}
