# Generated by Django 5.2.7 on 2025-10-21 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_household', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('lodging', 'Lodging'), ('food', 'Food'), ('transport', 'Transport'), ('activities', 'Activities'), ('other', 'Other')], default='lodging', max_length=24)),
                ('currency', models.CharField(default='THB', max_length=8)),
                ('fx_to_cad', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('weight_household', models.PositiveIntegerField(default=1)),
                ('weight_bev', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to='tracker.party')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_cad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_settlements', to='tracker.party')),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_settlements', to='tracker.party')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
