# Generated by Django 5.2.7 on 2025-10-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecentCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='THB', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fx_to_cad',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['date'], name='tracker_set_date_ba2bee_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['from_party', 'to_party'], name='tracker_set_from_pa_e55477_idx'),
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['date', 'base', 'quote'], name='tracker_fxr_date_79cad6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fxrate',
            unique_together={('date', 'base', 'quote')},
        ),
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='tracker.party'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to='tracker.person'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='tracker_exp_date_053070_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['currency'], name='tracker_exp_currenc_5009f7_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by'], name='tracker_exp_paid_by_6363b6_idx'),
        ),
        migrations.AddField(
            model_name='userrecentcurrency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['party'], name='tracker_per_party_i_36dada_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'party')},
        ),
        migrations.AddIndex(
            model_name='userrecentcurrency',
            index=models.Index(fields=['user', '-updated_at'], name='tracker_use_user_id_0ebab9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrecentcurrency',
            unique_together={('user', 'code')},
        ),
    ]
